### ISSUE TITLE
ローカルの middleman サーバで TypeError が発生する

### ISSUE THREAD

**Issue by tmd45** [feedforce/tech.feedforce.jp#183]
こちらの確認にて発見
https://github.com/feedforce/tech.feedforce.jp/pull/182#issuecomment-192059961

```
TypeError: no implicit conversion of nil into String
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/source/index.html.erb:8:in `+'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/source/index.html.erb:8:in `block (2 levels) in singleton class'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/source/index.html.erb:1:in `each'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/source/index.html.erb:1:in `each_with_index'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/source/index.html.erb:1:in `block in singleton class'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/source/index.html.erb:-16:in `instance_eval'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/source/index.html.erb:-16:in `singleton class'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/source/index.html.erb:-18:in `__tilt_70297623393480'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/rendering.rb:303:in `render_individual_file'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/rendering.rb:181:in `_render_with_all_renderers'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/rendering.rb:149:in `render_template'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb:127:in `block in render'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.14.2/lib/active_support/notifications.rb:161:in `instrument'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-core-3.3.12/lib/middleman-core/util.rb:41:in `instrument'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-core-3.3.12/lib/middleman-core/application.rb:235:in `instrument'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb:14:in `instrument'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-core-3.3.12/lib/middleman-core/sitemap/resource.rb:100:in `render'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:260:in `process_request'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:210:in `block in call!'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:209:in `catch'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:209:in `call!'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:195:in `call'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/rack-livereload-0.3.16/lib/rack/livereload.rb:23:in `_call'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/rack-livereload-0.3.16/lib/rack/livereload.rb:14:in `call'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/middleman-autoprefixer-2.3.0/lib/middleman-autoprefixer/extension.rb:43:in `call'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
        /Users/tmd45/work/src/github.com/feedforce/tech.feedforce.jp/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
        /Users/tmd45/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /Users/tmd45/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /Users/tmd45/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by tmd45** [comment]
Frontmatter の `authors: ` が指定されていない記事（その記事自体）を開くと同じエラーが発生する。

また index ページにその記事のインデックスが含まれると、同様にエラーになる。
（index ページでも `authors: ` を参照表示している箇所があるためと思われる）

**Comment by tmd45** [comment]
@masutaka も言ってたけど、 記事書き始めたら `authors: ` は埋めるだろうから問題はない。
`middleman article` のオプションに、日付だけじゃなくて authors も指定できたらいいんですけどね…

とりあえずこのエラーは気にしなくて良い。authors は忘れずに埋めてね！ということで。

**Comment by tmd45** [comment]
同じ轍を踏まないようにできたらいいんだけど、今はとりあえず共有まで(´・ω・`)

クローズするお。

**Comment by masutaka** [comment]
ありがとうございました！

**Comment by dkimura** [comment]
ここらへんのコードがダメっぽいのが原因かな…。
https://github.com/feedforce/tech.feedforce.jp/blob/master/source/index.html.erb#L17

**Comment by tmd45** [comment]
解決

```
author_data = author_info(article.data.authors) || 'Anonymous'
```

**Comment by masutaka** [comment]
:+1:

**Comment by tmd45** [comment]
確認してないテキトウコードなので信用してはいけない。実際その後に空判定で使ってるからあかんぞい。

**Comment by tmd45** [comment]
軽くコード追って、[キューバ](https://retrip.jp/articles/2793/)しのぎ良くない、ってところまで見た。
